# Appearance
appearance:
  # theme_day: minimal
  theme_night: minimal
  font: minimal
  font_size: S

# SEO
# meta:
#   favicon: 

marketing:
  seo:
    site_type: Person
    local_business_type: ''
    org_name: 'veronica chelu'
    description: 'Veronica Chelu'
  analytics:
    google_analytics: ''
    baidu_tongji: ''
  verification:
    google: ''
    baidu: ''

# Site header

header:
  navbar:
    enable: true
    align: r
    show_logo: true
    show_language: false
    show_day_night: false
    show_search: false
    highlight_active_link: true

# Site footer

footer:
  copyright:
    notice: '© {year} Veronica Chelu.'
    license:
      enable: false
      allow_derivatives: false
      share_alike: false
      allow_commercial: false

# Localization

# locale:
#   date_format: 'Jan 2, 2006'
#   time_format: '3:04 PM'
#   address_format: en-us

# Site features

features:
  syntax_highlighter:
    theme_light: github-dark
    theme_dark: dracula
  math:
    enable: true
  privacy_pack:
    enable: false
  repository:
    url: 'https://github.com/veronika.chelu'
    content_dir: content
    branch: main
  avatar:
    gravatar: false
    shape: circle
  comment:
    provider: ''
    disqus:
      shortname: ''
      show_count: true
    commento:
      url: ''
    giscus:
      repo: ''
      repo_id: ''
      category: ''
      category_id: ''
  search:
    provider: google
    algolia:
      app_id: ''
      api_key: ''
      index_name: ''
      show_logo: false
  map:
    provider: ''
    api_key: ''
    zoom: 15

# Extensions

extensions:
  cms:
    branch: main
    local_backend: false
  academicons:
    enable: true

# Security

security:
  # Allow frame for embedding speaker notes in slides
  allow_frame: true
